sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /kinect2/qhd/image_depth_rect
    queue_size: 5
    near_clipping_plane_distance: 0.5
    far_clipping_plane_distance: 4.5
    shadow_threshold: 0.2
    padding_scale: 5.0
    padding_offset: 0.03
    filtered_cloud_topic: filtered_cloud
